package com.example.catchcompass.storage;

import org.springframework.stereotype.Component;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.file.Files;
import java.nio.file.NoSuchFileException;
import java.nio.file.Path;
import java.time.LocalDate;
import java.util.UUID;

@Component
public class LocalPhotoStorage implements PhotoStorage {

    private final Path root;

    public LocalPhotoStorage(StorageProperties properties) throws IOException {
        this.root = properties.photoDirectory().toAbsolutePath().normalize();
        Files.createDirectories(this.root);
    }

    @Override
    public String store(byte[] content, String extension) {
        LocalDate today = LocalDate.now();
        String key = "%04d/%02d/%02d/%s.%s".formatted(
                today.getYear(),
                today.getMonthValue(),
                today.getDayOfMonth(),
                UUID.randomUUID(),
                extension);

        Path target = resolve(key);
        try {
            Files.createDirectories(target.getParent());
            Files.write(target, content);
        } catch (IOException e) {
            throw new UncheckedIOException("Could not store photo " + key, e);
        }
        return key;
    }

    @Override
    public byte[] load(String storageKey) {
        try {
            return Files.readAllBytes(resolve(storageKey));
        } catch (NoSuchFileException e) {
            throw new UncheckedIOException("Photo missing from storage: " + storageKey, e);
        } catch (IOException e) {
            throw new UncheckedIOException("Could not read photo " + storageKey, e);
        }
    }

    @Override
    public void delete(String storageKey) {
        try {
            Files.deleteIfExists(resolve(storageKey));
        } catch (IOException e) {
            throw new UncheckedIOException("Could not delete photo " + storageKey, e);
        }
    }

    /**
     * Resolves a key inside the storage root and refuses to leave it.
     *
     * <p>Keys are generated by this class, so this should never trigger. It is
     * here because "should never" and "cannot" are different guarantees, and
     * path traversal is the classic way file upload endpoints are exploited.
     */
    private Path resolve(String storageKey) {
        Path resolved = root.resolve(storageKey).normalize();
        if (!resolved.startsWith(root)) {
            throw new IllegalArgumentException("Storage key escapes the storage root");
        }
        return resolved;
    }
}
